### ISSUE TITLE
[JOSS Review] Mention `mpi4py` being required

### ISSUE THREAD

**Issue by 1313e** [mpi4jax/mpi4jax#100]
This issue is part of the JOSS Review in openjournals/joss-reviews#3419.

In order for `mpi4jax` to work, `mpi4py` is required, which is obvious.
However, for some, it might be logical to assume that `mpi4jax` will install `mpi4py` automatically correctly.
The problem however is that installing `mpi4py` is usually a bit of a pain to do correctly and rarely works properly, so it is much better to do it manually.
Therefore, I would advise putting in the README at the basic installation instructions that `mpi4py` must be installed already.

It might also be a good idea to make this clearer in the online documentation installation instructions.

**Comment by dionhaefner** [comment]
It should work fine most of the time, but yes there are pathologic cases where it doesn't work (e.g. globally pre-installed mpi4py). For this we have this section in the docs:

https://mpi4jax.readthedocs.io/en/latest/installation.html#selecting-the-mpi-distribution

I think the MPI shipped by mpi4py is OpenMPI-based, so this might also break when using a different vendor. Is this what you ran into @1313e ?

If @PhilipVinc doesn't beat me to it I can update the docs (to mention mpi4py earlier) when I'm back in August.

**Comment by 1313e** [comment]
The MPI shipped with `mpi4py` is usually MPICH2, not OpenMPI.
Anyway, simply mentioning that it is a good idea to install `mpi4py` manually before attempting to install `mpi4jax` in the README should be enough.

**Comment by dionhaefner** [comment]
I'm not sure whether I agree that it is generally good to install mpi4py beforehand. Anyway, I have added instructions for this case to README and docs. Turns out the installation works a bit differently when you choose to pre-install mpi4py.

Feel free to reopen if you feel that this isn't resolved.
