### ISSUE TITLE
[JOSS Review] Tests cannot be executed properly

### ISSUE THREAD

**Issue by 1313e** [mpi4jax/mpi4jax#102]
This issue is part of the JOSS Review in openjournals/joss-reviews#3419.

I have installed `mpi4jax` properly (I think), but when I want to run the tests, the process crashes at `tests/test_examples.py::test_shallow_water_demo` with no errors whatsoever.
Normally I would say that this is an indication of a SegmentationFault in C, but `mpi4jax` does not use C.

Below is what my actual output is
```
x1313e@CyborgU:~/Bureaublad/mpi4jax$ pytest -vvv
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/x1313e/.conda/envs/mpi4jax/bin/python
cachedir: .pytest_cache
MPI vendor: ('MPICH', (3, 3, 2))
MPI rank: 0
MPI size: 1
rootdir: /home/x1313e/Bureaublad/mpi4jax, configfile: pyproject.toml, testpaths: tests
plugins: cov-2.12.1
collected 108 items                                                                                                                                                                                               

tests/test_decorators.py::test_envvar_parsing PASSED                                                                                                                                                        [  0%]
tests/test_decorators.py::test_missing_omnistaging PASSED                                                                                                                                                   [  1%]
tests/test_decorators.py::test_ensure_gpu_ext PASSED                                                                                                                                                        [  2%]
tests/test_examples.py::test_shallow_water_demo
```
The fourth test never runs, as I get control back of the terminal.

If I disable that test to see if the others work, I get the same issue with the test called `tests/collective_ops/test_allgather.py::test_allgather`, so it seems there are multiple of these.

Any ideas what is going wrong here?

**Comment by dionhaefner** [comment]
It looks like a broken MPI or `mpi4py` installation. @PhilipVinc has more experience with debugging broken installs, so maybe he can weigh in :)

I'm on vacation for 3 weeks now, if this is still standing I can take care of it.

Anyhow, more information on how you installed MPI, mpi4py, and mpi4jax is probably in order. Could also be a duplicate of https://github.com/mpi4jax/mpi4jax/issues/91, so please make sure you have `jaxlib>=0.1.69`.

**Comment by dionhaefner** [comment]
It could also be a duplicate of #86 if you installed mpi4py before mpi4jax.

**Comment by PhilipVinc** [comment]
That bug should only manifests if you have non multiple of 4 hardware threads, IIRC.
To rule it out you should update to the last jaxlib release.

**Comment by 1313e** [comment]
I installed the entire package plus `jaxlib` yesterday from `pip` in a new environment, so I am assuming that those are the latest versions.

All packages were installed using `pip`, where I installed `mpi4py` before installing `mpi4jax`.
I can use `mpi4py` just fine, all the communication methods that I tried to use execute as I expect them to.

**Comment by dionhaefner** [comment]
I can't reproduce this. Which Linux flavor is this? How did you install MPICH?

**Comment by 1313e** [comment]
Ubuntu, and MPICH was installed automatically by `mpi4py`.
I know the latter is installed properly, as my own MPI scripts can be executed just fine

**Comment by dionhaefner** [comment]
> MPICH was installed automatically by mpi4py.

This sounds to me like you are mixing conda and pip, which we specifically advise against. mpi4py only ships with MPICH on conda (or on Windows).

That being said, I'm still unable to reproduce. I'm trying with this Dockerfile:

```dockerfile
FROM continuumio/miniconda3:latest

RUN conda create -n mpi4jax "python<3.8" mpi4py gxx_linux-64

SHELL ["conda", "run", "-n", "mpi4jax", "/bin/bash", "-c"]

WORKDIR /opt
RUN git clone https://github.com/mpi4jax/mpi4jax.git

WORKDIR /opt/mpi4jax
RUN pip install jax jaxlib
RUN pip install -e .[dev]

ENTRYPOINT ["conda", "run", "-n", "mpi4jax", "/bin/bash", "-c"] 
```

Build and run via

```bash
$ docker build -t mpi4jax .
$ docker run mpi4jax pytest
```

Output:

```
============================= test session starts ==============================
platform linux -- Python 3.7.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
MPI vendor: ('MPICH', (3, 3, 2))
MPI rank: 0
MPI size: 1
rootdir: /opt/mpi4jax, configfile: pyproject.toml, testpaths: tests
plugins: cov-2.12.1
collected 108 items

tests/test_decorators.py ...                                             [  2%]
tests/test_examples.py .                                                 [  3%]
tests/test_flush.py .                                                    [  4%]
tests/test_invalid_jaxlib.py ............                                [ 15%]
tests/test_validation.py ....                                            [ 19%]
tests/collective_ops/test_allgather.py ....                              [ 23%]
tests/collective_ops/test_allreduce.py ...............                   [ 37%]
tests/collective_ops/test_allreduce_matvec.py ........................   [ 59%]
tests/collective_ops/test_alltoall.py ...                                [ 62%]
tests/collective_ops/test_barrier.py .                                   [ 62%]
tests/collective_ops/test_bcast.py ....                                  [ 66%]
tests/collective_ops/test_common.py ...                                  [ 69%]
tests/collective_ops/test_gather.py ....                                 [ 73%]
tests/collective_ops/test_reduce.py ....                                 [ 76%]
tests/collective_ops/test_scan.py ....                                   [ 80%]
tests/collective_ops/test_scatter.py ...                                 [ 83%]
tests/collective_ops/test_send_and_recv.py sssssss                       [ 89%]
tests/collective_ops/test_sendrecv.py sssssssssss                        [100%]

=============================== warnings summary ===============================
../conda/envs/mpi4jax/lib/python3.7/site-packages/flatbuffers/compat.py:19
  /opt/conda/envs/mpi4jax/lib/python3.7/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/test_examples.py::test_shallow_water_demo
  /opt/mpi4jax/tests/../examples/shallow_water.py:35: UserWarning: Could not import tqdm, can't show progress bar
    warnings.warn("Could not import tqdm, can't show progress bar")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 90 passed, 18 skipped, 2 warnings in 14.19s ==================
```


Do you see anything you did differently from what is done in the Dockerfile?

**Comment by 1313e** [comment]
`mpi4py` installs MPICH automatically on both `conda` and `pip` if you have no valid MPI distribution available.
On Windows it does not do that, as only Microsoft MPI will work on Windows (I know, as I use both Windows and Linux).
I however tried using solely `pip` to install everything, and that gives me the exact same problem as when I install everything using `conda`.
The above in the Dockerfile is exactly how I installed `mpi4jax`.

**Comment by dionhaefner** [comment]
> mpi4py installs MPICH automatically on both conda and pip if you have no valid MPI distribution available.

That doesn't seem right. Just [look at the PyPI page](https://pypi.org/project/mpi4py/#files), you can see that there's no wheels for Linux, only Windows. Installing via pip definitely doesn't give you `mpirun` or `mpicc` executables. I have verified this in a clean Docker image.

As a last attempt to debug this, could you try

```bash
$ pip uninstall mpi4jax
$ pip install -e .[dev] --no-build-isolation --no-cache
$ pytest
```

and see if it changes anything?

**Comment by 1313e** [comment]
Sorry for taking so long, had a lot of business to take care off on my end.

On this PC, yes, I have a valid MPI distribution, as I need it for my work.
However, as far as I know, Linux does not come with its own MPI distribution and I have never installed one myself.
I always get it through `mpi4py`.

I tried to execute the script you gave me above, but that results in the same immediate crash with no errors thrown at all.

Afterward, I tried doing it again, but this time in Docker and on a supercomputer.
It seems to work just fine on both, so either there is something funny going on on my PC or MPICH2 is being weird.
On the supercomputer, I installed `mpi4jax` the exact same way as I did on my personal PC (which also means throwing `pip` and `conda` together), and that worked fine.
So, I am happy to close this issue now, but this might be something to keep in mind if others encounter the same problem, as I have absolutely no idea what is different between the installation I used on my machine and the supercomputer.

**Comment by dionhaefner** [comment]
Sure, let's leave it at that for now and see if it comes up again in the future.

> However, as far as I know, Linux does not come with its own MPI distribution and I have never installed one myself.

I usually just install OpenMPI via

```bash
$ sudo apt install libopenmpi-dev
```
