### ISSUE TITLE
MLIR translation rule for primitive 'allreduce_mpi' not found for platform tpu

### ISSUE THREAD

**Issue by sholtodouglas** [mpi4jax/mpi4jax#123]
Hi team! 

I've keen to explore mpi4jax for faster pipeline parallelism in LLM training than with an RPC solution like Ray. 

I'm currently working with a cluster of a couple of 4 v2-8s for testing.  MPI works fine - but when I try to run the basic mpi4jax example I get the error

` 'NotImplementedError: MLIR translation rule for primitive 'allreduce_mpi' not found for platform tpu'. `

On re-reading, the library does indeed say 'to entire CPU and GPU clusters' - though I had assumed this would include TPUs. Is there TPU support (e.g. is it a versioning error?)  - and if there isn't, do you have any advice about what solutions I should explore instead for pipeline parallelism using jax? 

Thanks :)

**Comment by PhilipVinc** [comment]
Hi!
Indeed Mpi4jax does not support at all TPUs. Maybe we should state explicitly that.

The issue at hand is that MPI does not exist on such accelerators.

You can still use mpi4jax, if you ensure that you love to the CPU the data before the call to mpi4jax, but you won't be able to execute it directly on TPU data.

There's some experimental stuff like xmap and global device array in jax. It's totally undocumented, but it is kind of a reimplementation of MPI on tpus.

**Comment by sholtodouglas** [comment]
That makes sense! Thank you for the swift response :) 

Got it! I've been using xmap within each node to remap the devices and do megatron style parallelism. 

With global device array / multi-host jax, does that work if I have 4 separate tpu v2-8s (as provided by TFRC), or would I need to use one v2-32?

**Comment by PhilipVinc** [comment]
No idea. I've never used TPUs.
I suspect that experimental.gda should work with multiple allocations but... 
you're better off asking in the jax repo.

**Comment by sholtodouglas** [comment]
Can do - thank you :)

**Comment by dionhaefner** [comment]
> The issue at hand is that MPI does not exist on such accelerators.

It's worse than that: There is no XLA custom call mechanism on TPU, so we can't even support it with implicit copies to CPU.
