### ISSUE TITLE
Is collective communication within a specific group instead of the communicator supported?

### ISSUE THREAD

**Issue by ntlm1686** [mpi4jax/mpi4jax#185]
From the arguments of CC ops, I only see the comm argument.

**Comment by dionhaefner** [comment]
I've never tried it, but you should be able to use [`MPI.Comm.Create(group)`](https://mpi4py.readthedocs.io/en/stable/reference/mpi4py.MPI.Comm.html#mpi4py.MPI.Comm.Create). Does that work?

**Comment by ntlm1686** [comment]
Yes, it works. Thanks.
