### ISSUE TITLE
Is any model zoo or well-known case for mpi4jax deployment?

### ISSUE THREAD

**Issue by Zantares** [mpi4jax/mpi4jax#208]
Where do I find a model zoo or well-known case (e.g. RN50, BERT or something else) for mpi4jax?

**Comment by dionhaefner** [comment]
mpi4jax is a low-level tool for manual MPI communication. It is not meant as a framework to implement models in.

You are welcome to look at other tools that [depend on mpi4jax](https://github.com/mpi4jax/mpi4jax/network/dependents) to see if something fits your use case.
