### ISSUE TITLE
CUDA toolkit required if JAX with GPU support is installed via pip

### ISSUE THREAD

**Issue by maxbortone** [mpi4jax/mpi4jax#220]
I thought it might be worth mentioning, since I recently struggled to get `mpi4jax` with GPU support installed in a conda environment where JAX was installed via the suggested [pip method](https://jax.readthedocs.io/en/latest/installation.html#pip-installation-gpu-cuda-installed-via-pip-easier). JAX recommends this methods since it allows one to use up to date CUDA and cuDNN versions in the case your HPC system doesn't have them yet, so it's likely that a lot of people will use it.

I got `mpi4jax` installed properly in a newly created conda environment by first running
```
conda install cuda-nvcc -c conda-forge -c nvidia
```
to install relevant [cuda toolkit](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#conda-installation) packages, which are not available via pip and therefore not installed with JAX. In my specific case, this command installed the following:
```
_sysroot_linux-64~ conda-forge/noarch::_sysroot_linux-64_curr_repodata_hack-3-h69a702a_13
  binutils_impl_lin~ conda-forge/linux-64::binutils_impl_linux-64-2.40-hf600244_0
  binutils_linux-64  conda-forge/linux-64::binutils_linux-64-2.40-hbdbef99_2
  cuda-cccl_linux-64 conda-forge/noarch::cuda-cccl_linux-64-12.0.90-ha770c72_1
  cuda-cudart        conda-forge/linux-64::cuda-cudart-12.0.107-h59595ed_6
  cuda-cudart-dev    conda-forge/linux-64::cuda-cudart-dev-12.0.107-h59595ed_6
  cuda-cudart-dev_l~ conda-forge/noarch::cuda-cudart-dev_linux-64-12.0.107-h59595ed_6
  cuda-cudart-static conda-forge/linux-64::cuda-cudart-static-12.0.107-h59595ed_6
  cuda-cudart-stati~ conda-forge/noarch::cuda-cudart-static_linux-64-12.0.107-h59595ed_6
  cuda-cudart_linux~ conda-forge/noarch::cuda-cudart_linux-64-12.0.107-h59595ed_6
  cuda-driver-dev_l~ conda-forge/noarch::cuda-driver-dev_linux-64-12.0.107-h59595ed_6
  cuda-nvcc          conda-forge/linux-64::cuda-nvcc-12.0.76-hba56722_10
  cuda-nvcc-dev_lin~ conda-forge/noarch::cuda-nvcc-dev_linux-64-12.0.76-ha770c72_1
  cuda-nvcc-impl     conda-forge/linux-64::cuda-nvcc-impl-12.0.76-h59595ed_1
  cuda-nvcc-tools    conda-forge/linux-64::cuda-nvcc-tools-12.0.76-h59595ed_1
  cuda-nvcc_linux-64 conda-forge/linux-64::cuda-nvcc_linux-64-12.0.76-h8a487aa_10
  cuda-version       conda-forge/noarch::cuda-version-12.0-hffde075_2
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-12.3.0-he2b93b0_2
  gcc_linux-64       conda-forge/linux-64::gcc_linux-64-12.3.0-h76fc315_2
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-12.3.0-he2b93b0_2
  gxx_linux-64       conda-forge/linux-64::gxx_linux-64-12.3.0-h8a814eb_2
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-64-3.10.0-h4a8ded7_13
  libgcc-devel_linu~ conda-forge/linux-64::libgcc-devel_linux-64-12.3.0-h8bca6fd_2
  libsanitizer       conda-forge/linux-64::libsanitizer-12.3.0-h0f45ef3_2
  libstdcxx-devel_l~ conda-forge/linux-64::libstdcxx-devel_linux-64-12.3.0-h8bca6fd_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_2
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.17-h4a8ded7_13
```

The cuda toolkit packages then allow `mpi4jax` to be installed via pip and built with the same CUDA versions as JAX. I did not have to set `CUDA_ROOT`, since the path to the`nvcc`  installed by conda points to the right root directory for all the necessary libraries.

I think a simple note in the documentation would be enough to help others in a similar situation.

**Comment by dionhaefner** [comment]
Good point. Not sure how we could fix this, unless we want to provide pre-built wheels with the same CUDA versions that JAX uses.

**Comment by PhilipVinc** [comment]
Jax recently changed things such that cuda is picked up from the cuda pypi wheels and cannot be overriden
https://github.com/google/jax/blob/1e810983fa7331a1ff18941e484b2a732c785e9d/.bazelrc#L86

So we should do the same: if `cudnn` and `cuda` are installed through pypi, we should force download of `nvcc` from pypi at build time and use it to build...

not sure how easy

**Comment by dionhaefner** [comment]
Is `nvcc` available through pypi?

**Comment by PhilipVinc** [comment]
A bit hackish but seems yes... 
https://pypi.org/project/nvidia-cuda-nvcc/

**Comment by PhilipVinc** [comment]
Ah wait, no... here https://pypi.org/project/nvidia-cuda-nvcc-cu12/ and https://pypi.org/project/nvidia-cuda-nvcc-cu11/ which are already jaxlib dependencies

**Comment by dionhaefner** [comment]
Okay, so this probably works out of the box?

```bash
$ pip install jax[cuda12_pip]
$ pip install mpi4jax --no-build-isolation
```

**Comment by maxbortone** [comment]
It didn't work in my case, as it doesn't seem to find the path to the pypi `nvcc`

**Comment by PhilipVinc** [comment]
Hi @maxbortone , It turns out that we recently managed to fix those issues in mpi4jax. See the updated installation instructions!

It should now be possible to simply do 

```python
pip install jax[cuda12_pip] -f ...
pip install --no-build-isolation mpi4jax
```

without any requirement for cuda being manually managed!
