### ISSUE TITLE
Unexpected behavior with JIT'ing allreduce

### ISSUE THREAD

**Issue by coreyjadams** [mpi4jax/mpi4jax#229]
I've encountered a strange behavior when using mpi4jax that has, in retrospect, been plaguing me for months.  I've managed to put it into a reproducer here:

https://gist.github.com/coreyjadams/6640c00c3dc0f202989cc964b8995214

(UPDATE: Here is an even simpler reproducer: 
https://gist.github.com/coreyjadams/3491879671467a72f102e2407d1890ee - I am able to make a buffer size large enough repeated allreduce breaks)

This code is standalone, you can just run it with `mpirun -n 1 python cg_test.py`.  It runs a Conjugate Gradient solve on synthetic data, where the use case is we have a factorization of the matrix A (of Ax=b fame) into a jacobian of shape (n_samples, n_params).  I have noticed that if the number of parameters (n_params) is small enough, mpi4jax works alright.  Above a threshold, it starts to produce strange results but ONLY if I use JIT.  I even tried introducing an mpi barrier to force the `allreduce` operation to complete - assuming I am using the tokens correctly - and that has not succeeded.

I found in some tests that the parameter size of 11963 was a turning point for when the CG algorithm really started breaking down, which is why I'm using it below, but it seems to be a red herring.  The real situation appears to be that jitting this allreduce produces unstable results: you will get different numbers running this script repeatedly, but ONLY in the situation of using mpi4jax's allreduce AND applying JIT to it.

I've reproduced this on two different systems using CUDA GPUs and seen it both times.  I've tested on CPU and it worked exactly as expected.

Summary: mpi4jax's `allreduce` function appears to have a bug when using data on CUDA gpus (routing through the CPU, in this case, haven't tested GPU-aware MPI) when JIT is applied.

If you run that out of the box,  you'll get these results:
```bash
NO  JIT - MPI: True, n_params: 11962, residual: 3.157265166369743.
YES JIT - MPI: True, n_params: 11962, residual: 9.479986947810453.
NO  JIT - MPI: True, n_params: 11963, residual: 3.549211138934023.
YES JIT - MPI: True, n_params: 11963, residual: 8.920987131893863.
NO  JIT - MPI: False, n_params: 11962, residual: 3.157265166369743.
YES JIT - MPI: False, n_params: 11962, residual: 3.1572651663697435.
NO  JIT - MPI: False, n_params: 11963, residual: 3.549211138934023.
YES JIT - MPI: False, n_params: 11963, residual: 3.549211138934023.
```

If you increase the number of iterations to 500, you get this:
```bash
No  JIT - MPI: True, n_params: 11962, residual: 0.00018166722894453279.
YES JIT - MPI: True, n_params: 11962, residual: 257.7061756863171.
NO  JIT - MPI: True, n_params: 11963, residual: 0.00014933259546807327.
YES JIT - MPI: True, n_params: 11963, residual: 211.88027991643523.
NO  JIT - MPI: False, n_params: 11962, residual: 0.00018166722894453279.
YES JIT - MPI: False, n_params: 11962, residual: 0.0001816672289445146.
NO  JIT - MPI: False, n_params: 11963, residual: 0.00014933259546807327.
YES JIT - MPI: False, n_params: 11963, residual: 0.0001493325954680718.
```

**Comment by PhilipVinc** [comment]
Is this with `MPI4JAX_USE_CUDA_MPI=1` ? If yes/no, can you try with no/yes to further pinpoint the issue?

**Comment by coreyjadams** [comment]
The mpi I have installed locally doesn't have CUDA support, I am using `MPI4JAX_USE_CUDA_MPI=0`. with MPI4JAX_USE_CUDA_MPI=1, it breaks the entire application.

I can go test on our cluster, to see if it makes a difference.

**Comment by coreyjadams** [comment]
A datapoint: On A100s, I see that I need a bigger buffer size to reproduce this, and it is without CUDA-aware mpi.  

```bash 
❯ MPI4JAX_USE_CUDA_MPI=0 python cg_test.py
NO  JIT - MPI: True, n_params: 21962, residual: 0.0001680838132421797.
YES JIT - MPI: True, n_params: 21962, residual: 29436.83724445558.
NO  JIT - MPI: True, n_params: 11963, residual: 0.00014933259546807433.
YES JIT - MPI: True, n_params: 11963, residual: 0.000149332595468078.
NO  JIT - MPI: False, n_params: 21962, residual: 0.0001680838132421797.
YES JIT - MPI: False, n_params: 21962, residual: 0.00016808381324217626.
NO  JIT - MPI: False, n_params: 11963, residual: 0.00014933259546807433.
YES JIT - MPI: False, n_params: 11963, residual: 0.000149332595468078.
```

**Comment by dionhaefner** [comment]
Problems like these are almost always due to incorrect token management. The GPU compiler is more aggressive than CPU so it makes sense why it would only appear there.

Have you tried whether using `notoken` mode fixes the issue?

```bash
$ export MPI4JAX_PREFER_NOTOKEN=1
# ... run your test script ...
```

**Comment by coreyjadams** [comment]
Just tried - unfortunately it doesn't change anything.  The `notoken` mode fails in the same way.

A few things I've noticed as I explore this strange behavior, using the `allreduce` example above (the second, simpler reproducer):
- The allreduce behavior appears to be correct for the first `k` entries, where `k` varies from run to run but is typically within 10% of the typical value: in fp64, I can allreduce vectors of about `k=38000` length.  In fp32, is not quite double, about `k=75000` length is correct.
- The incorrect features are all incorrect in the same way.  In the allreduce example above, I scale the vector by -0.99 and allreduce, repeatedly.  I can compare the final output to the expected output = `(0.99)**N * input`  I see the ratio for the first 5 elements looks like this: `[[1.], [1.], [1.],  [1.], [1.]]`, while the ratio for the last 5 elements looks like this: `[[0.60500607], [0.60500607],  [0.60500607], [0.60500607], [0.60500607]]`.    If you do the math, that is `0.99**50` meaning the allreduce missed 50 times.  It isn't always 50, in fact it's not deterministic how many times it fails.  But it's always consistent across the back end of the vector where it has failed (and the front of the vector is right!)

Any other debugging tips?  I can open an issue with JAX itself too if this is likely a token management issue.

**Comment by dionhaefner** [comment]
Can you post / upload the output you get when running with `MPI4JAX_DEBUG=1`?

**Comment by coreyjadams** [comment]
Here you go:
https://gist.github.com/coreyjadams/ad7ba4d544822d14a8e9bd1b9849e004

**Comment by dionhaefner** [comment]
Alright that was a tough nut. Could you try whether the fix in #230 works for you?

**Comment by coreyjadams** [comment]
Your changes surprise me: I would not expect switching from cudaMemCpy to cudaMemCpyAsync to ...  enforce synchronization?  

Either way, though, I can confirm it's fixed on both my laptop and on A100.  I really appreciate you looking into it!

**Comment by coreyjadams** [comment]
Update; It's working multi-node now too, with rather large memory buffers copying successfully.  I think the fix is successful!
