### ISSUE TITLE
MPI4py 4 breaks our install

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#249]
> The mpi4py.get_config function returns an empty dictionary.

breaks us because we do 

```python
        config = mpi4py.get_config()
        mpi_compiler = os.environ.get("MPI4JAX_BUILD_MPICC", config["mpicc"])
        mpi_cmd = shlex.split(mpi_compiler)
```

**Comment by PhilipVinc** [comment]
I implemented a bandaid by limiting compatibility with mpi4py < 4. 

We still need to solve this.

**Comment by dionhaefner** [comment]
@PhilipVinc Did you dig into what's going wrong here? Why is the config dict not populated anymore?

**Comment by PhilipVinc** [comment]
Seems a deliberate choice. Unsure why. 

https://github.com/mpi4py/mpi4py/pull/425
