### ISSUE TITLE
mpi4jax vs. mpi4py for cpu only

### ISSUE THREAD

**Issue by kchenhyd** [mpi4jax/mpi4jax#267]
Hi, 

I'm new to mpi4jax and have one question about the capability of mpi4jax against mpi4py. I have a code written in JAX that needs to evaluate 10000 individual functions, which has been successfully parallelized using mpi4py by distributing the 10000 functions into multiple cpu cores. I didn't see any issue while using mpi4py, so what's the benefit of mpi4jax if I don't use GPU/TPU? Any comments are appreciated. 

Thanks.

**Comment by dionhaefner** [comment]
mpi4jax is useful if you want to execute MPI operations from within JIT compiled blocks. If your parallelism is purely on the outer loop level (e.g. by mapping a JITed function across a large number of arguments), there's no reason to reach for mpi4jax.

**Comment by kchenhyd** [comment]
> mpi4jax is useful if you want to execute MPI operations from within JIT compiled blocks. If your parallelism is purely on the outer loop level (e.g. by mapping a JITed function across a large number of arguments), there's no reason to reach for mpi4jax.

Thanks for your explanation.
