### ISSUE TITLE
MPI4JAX_DEBUG and buffered output

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#81]
I was recently debugging some nasty deadlock and ended up `instrumenting` mpi4jax in thef ollowing ways:

Add to all print statements inside the cython module `flush=True` to flush the messages immediately, otherwise some messages might not be flushed before the deadlock occurs. Does it make sense for us to do it by default?
(Indeed there exists `python -u` that does that, but i did not know it and found out only later...)

To actually be sure about what was causing the deadlock, i added a message after every mpi operation to be sure that they finished, printing that the operation was done and the pointer of the input/output arrays (to actually match operations).

In the end the deadlock was in the python code (actually, it happened while compiling jax code) but for a while i thought it was in mpi4jax and so until i added those bnefore-and-after logs on messages i had the doubt.

Does it make sense to add those?

**Comment by dionhaefner** [comment]
We used to have flushing by default, I think it's a good idea to add it back.

About the tracing, I don't really see how that is generally useful. I think we can be confident that pointer addresses are consistent, at least we never observed anything pointing towards the contrary. How about we leave it out for now, and if we feel that we need this again we can add it?

**Comment by PhilipVinc** [comment]
good.

About the tracing, sorry, I was not very clear.
What i meant is that in our cython module we have calls to mpi like

```python
def mpi_function(x,y)
 if debug:
    print("running this mpi function")
  mpi_function(x,y)
```

However it's hard to know if there is a deadlock when executing one of those functions.
To be 100% sure there is no deadlock, we should have something like:

```python
def mpi_function(x,y)
 if debug:
    print("running this mpi function")
  mpi_function(x,y)
 if debug:
    print("finished running this mpi function")
```

That is all. 

Then, about printing the pointer addresses, it's not really because they  might get mixed up in the call (i don't think they can), but rather because if you have several mpi calls interleaved it's an easy way to check what  RUNNING print has a correpsonding FINISHED print.

**Comment by dionhaefner** [comment]
In this case we could also generate a random unique ID for each call, should be easier to match than a pointer address. But let's leave this until we need it again.
