### ISSUE TITLE
Pytree support

### ISSUE THREAD

**Issue by louiskirsch** [mpi4jax/mpi4jax#82]
Awesome work on the library!
I often have pytrees of arrays that I want to send via mpi. Due to the current token management I can not simply
```
new_tree = jax.tree_map(functools.partial(mpi4jax.allreduce, comm=comm), tree)
```

Correct? Is there a simple workaround?

**Comment by dionhaefner** [comment]
Hey,

> Awesome work on the library!

Glad you like it.

You could solve your problem with some state that you update within your mapped function:

```python
token = jax.lax.create_token()

def allreduce_tree(leaf):
    global token
    res, token = mpi4jax.allreduce(leaf, comm=comm, token=token)
    return res

new_tree = jax.tree_map(allreduce_tree, tree)
```

This question actually gave me some inspiration to decouple that into a context manager. So you could do

```python
with mpi4jax.token_context():  # automatically injects and updates tokens
    new_tree = jax.tree_map(lambda leaf: mpi4jax.allreduce(leaf, comm=comm)[0], tree)
```

Would that solve your problem?

**Comment by louiskirsch** [comment]
Yes that's a good solution. Thank you!
