### ISSUE TITLE
Cannot find result of scattered array?

### ISSUE THREAD

**Issue by ISDementyev** [mpi4jax/mpi4jax#84]
Hello everyone, 

I am currently trying to run a simple script in Jupyter that takes a 4 x 2 array and scatters it to all available cores (there are 4). Afterwards, each element in the scattered 1 x 2 array is multiplied by 2. Here's the script.

```python
%%file test2.py
from time import time
from mpi4py import MPI
import jax
import numpy as np
import jax.numpy as jnp
import mpi4jax

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

time_init = time()
print("hello from rank", rank)

@jax.jit
def foo():
    if rank == 0:
        arr = jnp.arange(1,9).reshape((4, 2))
        print(arr)
        arr_sum, data = mpi4jax.scatter(arr, root=0, comm=comm)
        print(arr_sum)
        print("This took", time() - time_init, "s")

foo()
arr_sum *= 2
```

And to execute, I write the following:

```python
!mpirun -np 4 -x PMIX_MCA_gds=^ds12 python test2.py | tee finding_scatter.txt
```

the `-x PMIX_MCA_gds=^ds12` is used to suppress the output that is [sometimes seen](https://github.com/open-mpi/ompi/issues/7516)

However, whenever I try calling the scattered data after scattering, it doesn't show up - and I get this error:
```
hello from rank 0
hello from rank 1
hello from rank 3
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    arr_sum *= 2
NameError: name 'arr_sum' is not defined
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    arr_sum *= 2
NameError: name 'arr_sum' is not defined
Traced<ShapedArray(int32[4,2])>with<DynamicJaxprTrace(level=0/1)>
Traced<ShapedArray(int32[2])>with<DynamicJaxprTrace(level=0/1)>
This took 0.009289026260375977 s
hello from rank 2
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    arr_sum *= 2
NameError: name 'arr_sum' is not defined
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    arr_sum *= 2
NameError: name 'arr_sum' is not defined
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30243,1],1]
  Exit code:    1
```

What's going on? From the error itself, I get that it's trying to search for `arr_sum` but it cannot find it because it's apparently not defined. But how can that be, since I've presumably scattered a fragment to each core? Shouldn't assigning `arr_sum` to each scattered array fragment be enough to define it, thereby allowing each core to automatically identify their respective scattered fragment and perform calculations with them? I am trying to run mpi4jax as analogously as I would I run regular MPI4Py code, but it doesn't seem to be working. I've tried putting the scatter code anywhere else but in the `if rank == 0` statement, and that doesn't work either. My guess is that there is probably some syntax or formatting issue that I cannot find in my `test2.py` file.

**Comment by PhilipVinc** [comment]
You don’t have a return statement in foo?

**Comment by PhilipVinc** [comment]
Also this won’t get executed on other ranks so it will deadlock

**Comment by ISDementyev** [comment]
> Also this won’t get executed on other ranks so it will deadlock

Would scattering outside of the rank statement solve the issue then?

> You don’t have a return statement in foo?

I didn't think I needed it, because I had assumed that scattering would send the fragments to the cores and then I'd be able to do stuff with them.

**Comment by ISDementyev** [comment]
An update: I took your advice regarding the other ranks, and decided to make the scattering happen outside of an if statement:
```python
%%file test2.py
from time import time
from mpi4py import MPI
import jax
import numpy as np
import jax.numpy as jnp
import mpi4jax

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
time_init = time()

print("hello from rank", rank)
# if rank == 0:
#     print(arr)    
#     print(arr_sum)
#     print("This took", time() - time_init, "s")

arr = jnp.arange(1,9).reshape((4, 2))
arr_sum, _ = mpi4jax.scatter(arr, root=0, comm=comm)
print(arr_sum, "from rank", rank)
```
However, this gave me the following output (after using the same execution code):

```
hello from rank 1
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
hello from rank 0
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
hello from rank 3
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[1 2] from rank 0
[[         3          4]
 [2135441077 -536868872]
 [-192741370      32647]
 [         0          0]] from rank 1
hello from rank 2
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[[         5          6]
 [         7          8]
 [-118602688      32667]
 [         0          0]] from rank 2
[[3 0]
 [0 0]
 [5 6]
 [7 8]] from rank 3
```
Is this supposed to be the output?

**Comment by dionhaefner** [comment]
Scatter is a special case where array shaped are expected to differ between root and non-root ranks. 

On root, the input should have shape `(nproc, n_1, ..., n_k)`. On non-root, it should have shape `(n_1, ..., n_k)`.

So you will need to pass a different input on non-root to get meaningful results. Actually I'm surprises your MPI library doesn't crash, since the received message is shorter than expected.

**Comment by PhilipVinc** [comment]
You want to do 

```python
arr = jnp.arange(1,9).reshape((4, 2))

result_shape = jnp.zeros(2, dtype=arr.dtype)
if rank == 0:
    arr_sum, _ = mpi4jax.scatter(arr, root=0, comm=comm)
else:
    arr_sum, _ = mpi4jax.scatter(result_shape, root=0, comm=comm)

print(arr_sum, "from rank", rank)

```

**Comment by ISDementyev** [comment]
> You want to do
> 
> ```python
> arr = jnp.arange(1,9).reshape((4, 2))
> 
> result_shape = jnp.zeros(2, dtype=arr.dtype)
> if rank == 0:
>     arr_sum, _ = mpi4jax.scatter(arr, root=0, comm=comm)
> else:
>     arr_sum, _ = mpi4jax.scatter(result_shape, root=0, comm=comm)
> 
> print(arr_sum, "from rank", rank)
> ```

This worked for me, thank you so much!

**Comment by ISDementyev** [comment]
@dionhaefner 

> So you will need to pass a different input on non-root to get meaningful results. Actually I'm surprised your MPI library doesn't crash, since the received message is shorter than expected.

Is this akin to what your colleague @PhilipVinc recommended?

**Comment by PhilipVinc** [comment]
Yes we are saying the same thing
Il 21 mag 2021, 22:46 +0200, ISDementyev ***@***.***>, ha scritto:

**Comment by ISDementyev** [comment]
Ok, I see. Well, if none of you mind, I'll close the issue. I think I've solved my biggest issues here. Again, thank you to both of you for helping.
