### ISSUE TITLE
Build system isolation messes with pre-installed mpi4py on clusters

### ISSUE THREAD

**Issue by dionhaefner** [mpi4jax/mpi4jax#86]
Example:

```bash
$ pip install -e .
$ ldd mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.cpython-38-x86_64-linux-gnu.so
	libmpi.so.40 => not found
```

```bash
$ pip install -e . --no-build-isolation
$ ldd mpi4jax/_src/xla_bridge/mpi_xla_bridge_cpu.cpython-38-x86_64-linux-gnu.so
	libmpi.so.12 => /groups/ocean/software/software_gcc2020/mpich/3.3.2/lib/libmpi.so.12 (0x00007f5713150000)
```

So what happens is that the pip build system isolation re-installs `mpi4py` from a wheel instead of using the one that is already on `PYTHONPATH` (and that is linked to the correct MPI library).

I think that build system isolation has caused a lot more problems than it has solved at this point. So my suggestion would be to disable it, and just require cython and mpi4py to be installed before running pip install.

**Comment by PhilipVinc** [comment]
Sorry for answering now.

I'd like the install process to be as simple as possible. 
Many users of netket are not very comfortable with mpi/environment variables/stuff and I've seen many messed up installs.

In theory, to install mpi4py one must always have the compilers already, so the only 'new' thing we would be asking is for Cython to be installed, right? 
BTW, is it possible to disable the isolation from setup.py?

**Comment by dionhaefner** [comment]
Yes, people would need to have Cython and mpi4py installed *before* invoking `pip install`. So `pip install mpi4jax` would give an `ImportError` if either of those isn't available. But in this case I think it's the lesser evil.

I haven't found a way to disable build system isolation entirely, but you can achieve essentially the same thing by removing everything from `build-system.requires`, and require it as runtime dependency instead.

**Comment by dionhaefner** [comment]
If you prefer we could also keep Cython in `build-system.requires` and just remove `mpi4py`. So the user's responsibility would be to make sure `mpi4py` is installed before installing `mpi4jax`, but nothing else.

**Comment by dionhaefner** [comment]
We now recommend to use `--no-build-isolation` in this case, which should do the trick.
