### ISSUE TITLE
Jax 0.2.14 breaks mpi4jax

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#88]
I wonder if one day jax will have a stable interface.

that day ain’t today.

https://github.com/netket/netket/runs/2800632364#step:10:3704

**Comment by dionhaefner** [comment]
If I see this correctly then `abstract_token` is found in `jax.core` in both new and old JAX. So this should work in both:

```python
from jax.core import abstract_token
```

> I wonder if one day jax will have a stable interface.

One can only dream...
