### ISSUE TITLE
[CI Broken] Segfaults on MacOs CI

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#91]
OpenMPI segfaults, MPICH gives errors

https://github.com/mpi4jax/mpi4jax/runs/2997619570?check_suite_focus=true
https://github.com/mpi4jax/mpi4jax/runs/2997619625?check_suite_focus=true

(I noticed this in NetKet since 2 weeks, so i rerun our test suite now to see if the issue is with mpi4jax and it seems it is).

**Comment by PhilipVinc** [comment]
I see that https://github.com/mpi4jax/mpi4jax/runs/2997619570?check_suite_focus=true#step:7:25 mentions line 15 of test_allreduce_matvec.py which corresponds to 

```
k1, k2, k3, k4, k5 = jax.random.split(jax.random.PRNGKey(seed), 5)
```

which is weird..

**Comment by dionhaefner** [comment]
FWIW, everything works fine on my Mac. Did you encounter this anywhere outside of GH Actions?

**Comment by PhilipVinc** [comment]
Yeah, on my mac too.
But it's kind of annoying...

I tried to ssh into the github actions tester and it segfaults approximately 25% of the time when running `pytest tests/collective_ops/test_allreduce_matvec.py`

**Comment by PhilipVinc** [comment]
Can reproduce on GA with

```python 
import jax
import jax.numpy as jnp
seed = 123
m, n = 5, 60
k1, k2, k3, k4, k5 = jax.random.split(jax.random.PRNGKey(seed), 5)
```

**Comment by PhilipVinc** [comment]
Ok, the CI failure disappears by downgrading jaxlib from current (`0.1.68`) to `0.1.67`.
Jax is `0.2.16`

**Comment by PhilipVinc** [comment]
Crossref:  https://github.com/google/jax/issues/7198

**Comment by PhilipVinc** [comment]
it was a jax bug. solved in the last release of jaxlib
